"""Collect step-1 validation JSON into tables (results/step1/summary.json, step1_tables.md)
and figures (figures/step1_*.png)."""
import glob, json, os
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from common import CFG, OUT, FIG

S1 = os.path.join(OUT, "step1")
L = CFG["box_L"]
INK, GRID = "#0b0b0b", "#e4e3df"
C_NB, C_2, C_4, C_ZA = "#eb6834", "#2a78d6", "#e87ba4", "#1baf7a"
BLUES = ["#86b6ef", "#5598e7", "#2a78d6", "#1c5cab", "#104281", "#0d366b"]
plt.rcParams.update({"font.size": 9, "axes.edgecolor": "#8a8984", "axes.grid": True,
                     "grid.color": GRID, "grid.linewidth": 0.6, "lines.linewidth": 1.5,
                     "legend.frameon": False, "figure.dpi": 130, "savefig.bbox": "tight"})
MASK_NOTE = "Conditional on the single-stream mask M (both runs); not an unconditional 2-pt statistic."


def load(pat):
    out = {}
    for p in sorted(glob.glob(os.path.join(S1, pat))):
        out[os.path.basename(p)[:-5]] = json.load(open(p))
    return out


def fmt(x, p=2):
    return f"{x:.{p}e}"


def main():
    lines = ["# Step 1 validation tables (generated by collect.py)", ""]
    summ = {}

    # ---------------- (a) ----------------
    A = load("a_N*_l*.json")
    if A:
        lines += ["## 1a. z = 24: LPT vs N-body Gaussianized fields, element by element", "",
                  f"Criterion (fixed before running): Pearson r >= {CFG['criteria']['a_min_pearson']} and "
                  f"rms(Δy) <= {CFG['criteria']['a_max_rms_dy']} for every N, refinement, R, weighting, order.", "",
                  "| N | level | mask frac | pair | R | 1−r (mass) | rms Δy (mass) | max|Δy| (mass) | 1−r (vol) | rms Δy (vol) | pass |",
                  "|---:|---:|---:|---|---:|---:|---:|---:|---:|---:|:---:|"]
        allp = True
        for k, d in sorted(A.items(), key=lambda kv: (kv[1]["N"], kv[1]["level"])):
            allp &= d["passed"]
            for p, pr in d["pairs"].items():
                for R, x in pr.items():
                    m, v = x["ym"], x["yv"]
                    lines.append(f"| {d['N']} | {d['level']} | {d['mask_frac']:.4f} | {p} | {R[1:]} | "
                                 f"{fmt(1 - m['pearson'])} | {fmt(m['rms_dy'])} | {fmt(m['max_abs_dy'])} | "
                                 f"{fmt(1 - v['pearson'])} | {fmt(v['rms_dy'])} | {'✔' if m['passed'] and v['passed'] else '✘'} |")
        summ["a_passed"] = bool(allp)
        lines += ["", f"**1a overall: {'PASS' if allp else 'FAIL'}**", ""]

    # ---------------- (b) ----------------
    B = load("b_N*_l*.json")
    if B:
        lines += ["## 1b. Invariance of the Gaussianized ξ under monotone transforms of δ (z = 0)", "",
                  f"Criterion: max |Δξ| (all bins and the zero-lag term) <= {CFG['criteria']['b_max_abs_dxi']:g}. "
                  "Transforms: log, cube, −1/ρ, asinh(10δ). " + MASK_NOTE, "",
                  "| N | level | model | R | max |Δξ| mass | max |Δξ| vol | ties before → after (max) | y identical | pass |",
                  "|---:|---:|---|---:|---:|---:|---:|:---:|:---:|"]
        allp = True
        for k, d in sorted(B.items(), key=lambda kv: (kv[1]["N"], kv[1]["level"])):
            allp &= d["passed"]
            for m, res in d["models"].items():
                for R, x in res.items():
                    t = x["transforms"]
                    dm = max(v["max_abs_dxi"]["mass"] for v in t.values())
                    dv = max(v["max_abs_dxi"]["vol"] for v in t.values())
                    ta = max(v["ties_after"] for v in t.values())
                    ident = all(v["y_identical"] for v in t.values())
                    ps = all(v["passed"] for v in t.values())
                    lines.append(f"| {d['N']} | {d['level']} | {m} | {R[1:]} | {dm:.1e} | {dv:.1e} | "
                                 f"{x['ties']} → {ta} | {'yes' if ident else 'no'} | {'✔' if ps else '✘'} |")
        summ["b_passed"] = bool(allp)
        lines += ["", f"**1b overall: {'PASS' if allp else 'FAIL'}**", ""]

    # ---------------- (c) ----------------
    C = load("c_N*_l*_z*.json")
    if C:
        lines += ["## 1c. Noise floors (reported, no pass/fail)", "",
                  "Seed floor: max over separation bins of the spread of ξ_y between tie-break seeds "
                  f"{CFG['tie_seeds']} (refinement level 0).  Refinement floor: max |ξ_y(level 1) − ξ_y(level 0)| "
                  "over bins with r ≥ 2 Δq (Δq = L/N, the level-0 element size), same seed. " + MASK_NOTE, ""]
        rows = []
        byk = {}
        for k, d in C.items():
            byk[(d["N"], d["level"], d["z"])] = d
        lines += ["| z | N | run | mask | R | ties (l0) | seed floor mass | seed floor vol | refine floor mass | refine floor vol | mask frac l0 / l1 |",
                  "|---:|---:|---|---|---:|---:|---:|---:|---:|---:|---:|"]
        floors = {}
        for (N, lv, z), d0 in sorted(byk.items(), key=lambda t: (-t[0][2], t[0][0], t[0][1])):
            if lv != 0:
                continue
            d1 = byk.get((N, 1, z))
            for key, x0 in d0["runs"].items():
                run, mk, R = key.split("|")
                x1 = d1["runs"].get(key) if d1 else None
                rf = {}
                for w in ("mass", "vol"):
                    if x1 is None:
                        rf[w] = np.nan; continue
                    r0 = np.array(x0[w]["r"], float); a0 = np.array(x0[w]["xi"], float)
                    a1 = np.array(x1[w]["xi"], float)
                    sel = np.isfinite(a0) & np.isfinite(a1) & (r0 >= 2 * L / N)
                    rf[w] = float(np.max(np.abs(a1[sel] - a0[sel]))) if sel.any() else np.nan
                p = mk.split(":")[1]
                mf0 = d0["mask_frac"][p]; mf1 = d1["mask_frac"][p] if d1 else np.nan
                floors[f"z{z:g}|N{N}|{key}"] = dict(seed_mass=x0["mass"]["seed_floor"], seed_vol=x0["vol"]["seed_floor"],
                                                   refine_mass=rf["mass"], refine_vol=rf["vol"])
                lines.append(f"| {z:g} | {N} | {run} | {p} | {R[1:]} | {max(x0['ties'])} | "
                             f"{x0['mass']['seed_floor']:.1e} | {x0['vol']['seed_floor']:.1e} | "
                             f"{rf['mass']:.1e} | {rf['vol']:.1e} | {mf0:.4f} / {mf1:.4f} |")
        summ["c_floors"] = floors
        lines += [""]
        fig_c(byk)

    # ---------------- (d) ----------------
    Dp = os.path.join(S1, "d.json")
    if os.path.exists(Dp):
        d = json.load(open(Dp))
        qs = np.array(d["quantiles"])
        lines += ["## 1d. Zel'dovich single-stream marginal vs Doroshkevich | det J > 0", "",
                  f"σ_lin(a=1) of the fixed-amplitude field = {d['sigma_lin_a1']:.4f}.  Theory: "
                  f"{CFG['test_d']['mc_samples']:.0e} Monte-Carlo draws (seed {CFG['test_d']['mc_seed']}). "
                  f"Band: {len(CFG['test_d']['extra_seeds'])} independent fixed-amplitude realisations "
                  f"(seeds {CFG['test_d']['extra_seeds']}) at N = {CFG['test_d']['N_band']}, level {CFG['test_d']['refine_band']}. "
                  f"Criterion: the study realisation at N = {CFG['test_d']['N_test']}, level {CFG['test_d']['refine_test']}, "
                  f"and the mean of the band realisations lie within {CFG['criteria']['d_nsigma']:g}σ "
                  "(σ = band scatter; σ/√8 for the mean) of theory at every quantile. Primary condition: the "
                  "single-stream mask; 'det J > 0' (V_e > 0) shown for reference.", "",
                  "| z | condition | weighting | max |nσ| study (N=256,l1) | max |nσ| band mean | pass |",
                  "|---:|---|---|---:|---:|:---:|"]
        for z, r in d["z"].items():
            for cond in ("mask", "detpos"):
                for w in ("mass", "vol"):
                    x = r[cond][w]
                    lines.append(f"| {z} | {cond} | {w} | {np.max(np.abs(x['nsig_study_Ntest'])):.2f} | "
                                 f"{np.max(np.abs(x['nsig_band_mean'])):.2f} | {'✔' if x['passed'] else '✘'} |")
        summ["d_passed"] = d["passed_primary_mask"]
        lines += ["", f"**1d overall (mask condition): {'PASS' if d['passed_primary_mask'] else 'FAIL'}**", ""]
        fig_d(d)

    with open(os.path.join(S1, "summary.json"), "w") as f:
        json.dump(summ, f, indent=1, default=float)
    with open(os.path.join(OUT, "step1_tables.md"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print("\n".join(lines[:5]))
    print({k: v for k, v in summ.items() if k.endswith("passed")})


def fig_c(byk):
    """ξ_y level 0 vs level 1 for N-body and 4LPT at z = 0, N = 256 (refinement floor)."""
    for (N, lv, z), d in byk.items():
        if not (N == 256 and lv == 0 and z == 0.0):
            continue
        d1 = byk.get((N, 1, z))
        Rs = CFG["R_list"]
        fig, ax = plt.subplots(2, len(Rs), figsize=(2.6 * len(Rs), 5.2), sharex=True, gridspec_kw=dict(hspace=0.08, wspace=0.3))
        for j, R in enumerate(Rs):
            for run, col in (("nbody", C_NB), ("4lpt", C_4)):
                key = f"{run}|mask:4lpt|R{R:g}"
                for lvl, dd, ls in ((0, d, "-"), (1, d1, "--")):
                    if dd is None or key not in dd["runs"]:
                        continue
                    x = dd["runs"][key]["mass"]
                    r = np.array(x["r"], float); xi = np.array(x["xi"], float)
                    ax[0, j].plot(r, xi, ls, color=col, label=f"{run} level {lvl}")
                    if lvl == 1:
                        x0 = d["runs"][key]["mass"]
                        ax[1, j].plot(r, xi - np.array(x0["xi"], float), color=col, label=run)
            for a_ in ax[:, j]:
                a_.set_xscale("log"); a_.axvspan(0.5, 2 * L / N, color="#d9d8d3", alpha=0.6, lw=0)
            ax[0, j].set_title(f"R = {R:g} Mpc/h", fontsize=9)
            ax[1, j].axhline(0, color="#8a8984", lw=0.8); ax[1, j].set_xlabel("|Δq| [Mpc/h]")
        ax[0, 0].set_ylabel("ξ_y (mass-weighted)"); ax[1, 0].set_ylabel("level 1 − level 0")
        ax[0, 0].legend(fontsize=6.5)
        fig.suptitle(f"Refinement floor, z = 0, N = {N}³, mask = N-body ∩ 4LPT single-stream. Grey: r < 2Δq "
                     "(below the level-0 element scale, excluded from the floor).\n" + MASK_NOTE, fontsize=8, y=1.02)
        fig.savefig(os.path.join(FIG, "step1_c_refinement.png")); plt.close(fig)


def fig_d(d):
    qs = np.array(d["quantiles"])
    fig, ax = plt.subplots(1, 2, figsize=(10, 3.4), sharey=True, gridspec_kw=dict(wspace=0.08))
    for a_, w in zip(ax, ("mass", "vol")):
        for z, col in (("1", BLUES[1]), ("0", BLUES[4])):
            x = d["z"][z]["mask"][w]
            a_.plot(qs, x["nsig_study_Ntest"], "o-", color=col, ms=4, label=f"study realisation, z = {z}")
            a_.plot(qs, x["nsig_band_mean"], "s--", color=col, ms=3.5, mfc="white", label=f"8-realisation mean, z = {z}")
        c = CFG["criteria"]["d_nsigma"]
        a_.axhspan(-c, c, color="#d9d8d3", alpha=0.5, lw=0)
        a_.axhline(0, color="#8a8984", lw=0.8)
        a_.set_xscale("logit"); a_.set_xlabel("quantile of log ρ (single-stream Zel'dovich elements)")
        a_.set_title(f"{w}-weighted", fontsize=9)
    ax[0].set_ylabel("(measured − Doroshkevich) / σ_realisations")
    ax[0].legend(fontsize=7)
    fig.suptitle("Test 1d: Zel'dovich element densities in the single-stream mask vs Doroshkevich conditioned on det J > 0. "
                 "Grey band: ±3σ pass region.", fontsize=8, y=1.03)
    fig.savefig(os.path.join(FIG, "step1_d_doroshkevich.png")); plt.close(fig)


if __name__ == "__main__":
    main()
