"""Tables and figures: CIC vs phase-space-sheet density PDFs on the same snapshots.

    python analyze_sheet.py      (after run_sheet_pdf.py deposit + stats)

Writes results/summary.json, results/tables.md and figures/sheet_*.{png,pdf}.
"""
import json, os, sys
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
import config as C
import run_sheet_pdf as P

FIG = os.path.join(HERE, "figures"); os.makedirs(FIG, exist_ok=True)
RES = P.RES
C_ORD = {"1lpt": "#1baf7a", "2lpt": "#2a78d6", "3lpt": "#4a3aa8", "4lpt": "#e87ba4", "nbody": "#eb6834"}
LBL = {"1lpt": "Zel'dovich", "2lpt": "2LPT", "3lpt": "3LPT", "4lpt": "4LPT", "nbody": "N-body"}
INK, GRID = "#0b0b0b", "#e4e3df"
plt.rcParams.update({"font.size": 9, "axes.edgecolor": "#8a8984", "axes.labelcolor": INK,
                     "xtick.color": "#52514e", "ytick.color": "#52514e", "axes.grid": True,
                     "grid.color": GRID, "grid.linewidth": 0.6, "lines.linewidth": 1.5,
                     "legend.frameon": False, "figure.dpi": 130, "savefig.bbox": "tight"})
QLAB = ["0.1%", "1%", "10%", "50%", "90%", "99%", "99.9%"]
S1_TAGS = {"1lpt": "1lpt_N256", "2lpt": "2lpt_N256", "3lpt": "3lpt_N256", "4lpt": "4lpt_N256",
           "nbody": "nb_N256_m2_s100_ai0.04_log"}


def save(fig, name):
    for ext in ("png", "pdf"):
        fig.savefig(os.path.join(FIG, f"{name}.{ext}"))
    plt.close(fig)


def load():
    S = json.load(open(os.path.join(RES, "stats.json")))
    return S, S["runs"]


def get(R_, tag, est, R):
    return R_.get(f"{tag}|{est}", {}).get(f"R{R:g}")


def study1(model, R, paired=False):
    """Original study-1 CIC statistics (numpy snapshots, KDK PM) from its stats cache."""
    t = S1_TAGS[model] + ("_paired" if paired else "")
    p = os.path.join(C.SCRATCH, t + "_stats.npz")
    if R == 0 or not os.path.exists(p):
        return None
    z = np.load(p)
    return {k: z[f"R{R:g}_{k}"] for k in ("qV", "qM", "var", "S3", "S4")}


def load_tet():
    p = os.path.join(RES, "tetmass.json")
    return json.load(open(p)) if os.path.exists(p) else None


def tetq(T, tag, R):
    g = T.get(tag, {}).get(f"R{R:g}")
    return None if g is None else np.array(g["qM"])


def pct(x):
    return f"{100 * x:+.1f}%"


def main():
    S, R_ = load()
    Rs = S["R"]; qs = np.array(S["QS"])
    models = [m for m in P.MODELS if f"{m}_N256|sheet" in R_]
    summ = dict(quantiles=qs.tolist(), R=Rs, estimators=list(P.EST), sanity={}, estimator_diff={},
                vs_nbody={}, convergence={}, consistency={})
    L = ["# CIC vs phase-space-sheet density PDFs (generated by analyze_sheet.py)", "",
         "Same DiscoDJNative z = 0 snapshots (study-1 ICs) for both estimators; 256³ analysis mesh; "
         "top-hat R_s; volume weighting = cells equally, mass weighting = each cell by its deposited mass.", ""]

    # ---- 0. sanity -------------------------------------------------------------------------
    L += ["R_s = 0 denotes the raw 1.17 Mpc/h cells (no smoothing, no window deconvolution), a diagnostic "
          "outside the study-1 set R_s = 7–42 Mpc/h.", "",
          "## Estimator sanity (N = 256)", "",
          "| model | estimator | mean ρ (raw) | min ρ (raw) | min ρ_R, R_s = 7 | cells ρ_R ≤ 0, R_s = 7 |",
          "|---|---|---:|---:|---:|---:|"]
    for m in models:
        for e in P.EST:
            r = R_[f"{m}_N256|{e}"]; g = r["R7"]
            summ["sanity"][f"{m}|{e}"] = dict(mean=r["mean"], min_raw=r["min_raw"], min_R7=g["min"], neg_R7=g["neg"])
            L.append(f"| {LBL[m]} | {e} | {r['mean']:.6f} | {r['min_raw']:.4f} | {g['min']:.4f} | {g['neg']:.1e} |")
    L.append("")

    # ---- 1. estimator difference: sheet / CIC - 1 at fixed quantiles --------------------------
    L += ["## Sheet / CIC − 1 of 1+δ_R at fixed quantiles (N = 256, same snapshot)", ""]
    for w, wl in (("V", "volume"), ("M", "mass")):
        L += [f"### {wl}-weighted", "", "| model | R_s | " + " | ".join(QLAB) + " | σ² |",
              "|---|---:|" + "---:|" * (len(QLAB) + 1)]
        for m in models:
            for R in Rs:
                a, b = get(R_, f"{m}_N256", "sheet", R), get(R_, f"{m}_N256", "cic", R)
                d = np.array(a["q" + w]) / np.array(b["q" + w]) - 1
                summ["estimator_diff"][f"{m}|R{R:g}|{w}"] = d.tolist()
                L.append(f"| {LBL[m]} | {R:g} | " + " | ".join(pct(x) for x in d) +
                         f" | {pct(a['var'] / b['var'] - 1)} |")
        L.append("")

    # ---- 2. nLPT vs N-body with each estimator (the study-1 comparison) -----------------------
    L += ["## nLPT / N-body − 1 with each estimator (N = 256)", "",
          "Columns as in study 1: σ² ratio − 1; volume-weighted 0.1% and 99.9% quantiles; "
          "mass-weighted 99% and 99.9% quantiles of 1+δ_R.  'sheet (paired)' uses the θ+π realisation.", "",
          "| R_s | model | estimator | σ² | vol 0.1% | vol 99.9% | mass 99% | mass 99.9% | S₃ ratio |",
          "|---:|---|---|---:|---:|---:|---:|---:|---:|"]
    for R in Rs:
        for m in [x for x in models if x != "nbody"]:
            for e, suf in (("cic", ""), ("sheet", ""), ("sheet", "_paired")):
                a, b = get(R_, f"{m}_N256{suf}", e, R), get(R_, f"nbody_N256{suf}", e, R)
                if a is None or b is None:
                    continue
                qv = np.array(a["qV"]) / np.array(b["qV"]) - 1
                qm = np.array(a["qM"]) / np.array(b["qM"]) - 1
                row = dict(var=a["var"] / b["var"] - 1, vol0p1=qv[0], vol99p9=qv[-1], mass99=qm[-2],
                           mass99p9=qm[-1], S3=a["S3"] / b["S3"], qV=qv.tolist(), qM=qm.tolist())
                summ["vs_nbody"][f"{m}|R{R:g}|{e}{suf}"] = row
                L.append(f"| {R:g} | {LBL[m]} | {e}{' (paired)' if suf else ''} | {pct(row['var'])} | {pct(row['vol0p1'])} | "
                         f"{pct(row['vol99p9'])} | {pct(row['mass99'])} | {pct(row['mass99p9'])} | {row['S3']:.3f} |")
        L.append("")

    # ---- 3. resolution convergence of each estimator ---------------------------------------
    L += ["## Resolution convergence of each estimator", "",
          "Largest |shift| of the 1–99% quantiles against N = 256 (the study-1 metric), same analysis mesh.", "",
          "| model | R_s | estimator | N = 64 (V / M) | N = 128 (V / M) | 0.1% / 99.9% at N = 128 (V) |",
          "|---|---:|---|---:|---:|---:|"]
    for m in models:
        for R in (0.0, 7.0, 14.0):
            for e in P.EST:
                ref = get(R_, f"{m}_N256", e, R)
                cells = []; ext = ""
                for n in (64, 128):
                    g = get(R_, f"{m}_N{n}", e, R)
                    if g is None:
                        cells.append("–"); continue
                    dv = np.max(np.abs(np.array(g["qV"])[1:-1] / np.array(ref["qV"])[1:-1] - 1))
                    dm = np.max(np.abs(np.array(g["qM"])[1:-1] / np.array(ref["qM"])[1:-1] - 1))
                    summ["convergence"][f"{m}|R{R:g}|{e}|N{n}"] = dict(dq_V=dv, dq_M=dm,
                        tails_V=(np.array(g["qV"])[[0, -1]] / np.array(ref["qV"])[[0, -1]] - 1).tolist())
                    cells.append(f"{100 * dv:.2f}% / {100 * dm:.2f}%")
                    if n == 128:
                        t = np.array(g["qV"])[[0, -1]] / np.array(ref["qV"])[[0, -1]] - 1
                        ext = f"{pct(t[0])} / {pct(t[1])}"
                L.append(f"| {LBL[m]} | {R:g} | {e} | {cells[0]} | {cells[1]} | {ext} |")
    L.append("")

    # ---- 4. consistency with study 1 (original numpy snapshots, CIC) ------------------------
    L += ["## Consistency with study 1", "",
          "CIC on the DiscoDJNative snapshots vs the original study-1 CIC (numpy nLPT at 256³; numpy KDK PM, "
          "100 steps, for N-body). Largest |relative difference| over the 0.1–99.9% quantiles.", "",
          "| model | R_s | vol | mass | σ² |", "|---|---:|---:|---:|---:|"]
    for m in models:
        for R in Rs:
            s1, g = study1(m, R), get(R_, f"{m}_N256", "cic", R)
            if s1 is None or g is None:
                continue
            dv = np.max(np.abs(np.array(g["qV"]) / s1["qV"] - 1)); dm = np.max(np.abs(np.array(g["qM"]) / s1["qM"] - 1))
            summ["consistency"][f"{m}|R{R:g}"] = dict(dq_V=dv, dq_M=dm, dvar=g["var"] / float(s1["var"]) - 1)
            L.append(f"| {LBL[m]} | {R:g} | {100 * dv:.2f}% | {100 * dm:.2f}% | {pct(g['var'] / float(s1['var']) - 1)} |")
    L.append("")

    # ---- 5. gridless mass weighting from the tetrahedra -------------------------------------
    T = load_tet()
    if T:
        summ["tet"] = {}
        L += ["## Mass-weighted PDFs from the tetrahedra (no gridded weights)", "",
              "Every tetrahedron has mass Δq³/6, so an equal-weight sample over tetrahedra is mass-weighted. "
              "R_s = 0: stream density (Δq³/6)/|V_T| of each tetrahedron (unsmoothed, resolved to the tetrahedron "
              "scale). R_s > 0: the smoothed exact-sheet field at each tetrahedron centroid. "
              "Compared with the gridded mass weightings (each 1.17 Mpc/h cell weighted by its deposited mass).", "",
              "### Estimators on the same snapshot (N = 256): tet / CIC-cell − 1 and sheet-cell / CIC-cell − 1 of the mass-weighted quantiles", "",
              "| model | R_s | weighting | " + " | ".join(QLAB) + " |", "|---|---:|---|" + "---:|" * len(QLAB)]
        for m in models:
            for R in Rs:
                t = tetq(T, f"{m}_N256", R); c = get(R_, f"{m}_N256", "cic", R); sh = get(R_, f"{m}_N256", "sheet", R)
                if t is None:
                    continue
                for lab, arr in (("tetrahedra", t), ("sheet cells", np.array(sh["qM"]))):
                    d = arr / np.array(c["qM"]) - 1
                    summ["tet"][f"est|{m}|R{R:g}|{lab}"] = d.tolist()
                    L.append(f"| {LBL[m]} | {R:g} | {lab} | " + " | ".join(pct(x) for x in d) + " |")
        L += ["", "### nLPT / N-body − 1 of the mass-weighted quantiles, three weightings (N = 256)", "",
              "| R_s | model | weighting | 50% | 90% | 99% | 99.9% |", "|---:|---|---|---:|---:|---:|---:|"]
        for R in Rs:
            for m in [x for x in models if x != "nbody"]:
                for lab, suf in (("tetrahedra", ""), ("tetrahedra (paired)", "_paired")):
                    a_, b_ = tetq(T, f"{m}_N256{suf}", R), tetq(T, f"nbody_N256{suf}", R)
                    if a_ is None or b_ is None:
                        continue
                    d = a_ / b_ - 1
                    summ["tet"][f"vsnb|{m}|R{R:g}|{lab}"] = d.tolist()
                    L.append(f"| {R:g} | {LBL[m]} | {lab} | {pct(d[3])} | {pct(d[4])} | {pct(d[5])} | {pct(d[6])} |")
                for e in ("sheet", "cic"):
                    a_, b_ = get(R_, f"{m}_N256", e, R), get(R_, "nbody_N256", e, R)
                    d = np.array(a_["qM"]) / np.array(b_["qM"]) - 1
                    L.append(f"| {R:g} | {LBL[m]} | {e} cells | {pct(d[3])} | {pct(d[4])} | {pct(d[5])} | {pct(d[6])} |")
            L.append("")
        L += ["### Convergence of the tetrahedron mass weighting", "",
              "Largest |shift| of the 1–99% mass-weighted quantiles against N = 256; and the 99.9% quantile shift.", "",
              "| model | R_s | N = 64 | N = 128 | 99.9% at N = 64 / 128 |", "|---|---:|---:|---:|---:|"]
        for m in models:
            for R in Rs:
                ref = tetq(T, f"{m}_N256", R)
                if ref is None:
                    continue
                cells = []; tails = []
                for n in (64, 128):
                    g = tetq(T, f"{m}_N{n}", R)
                    if g is None:
                        cells.append("–"); tails.append("–"); continue
                    dq = np.max(np.abs(g[1:-1] / ref[1:-1] - 1))
                    summ["tet"][f"conv|{m}|R{R:g}|N{n}"] = dict(dq_M=dq, tail=g[-1] / ref[-1] - 1)
                    cells.append(f"{100 * dq:.2f}%"); tails.append(pct(g[-1] / ref[-1] - 1))
                L.append(f"| {LBL[m]} | {R:g} | {cells[0]} | {cells[1]} | {tails[0]} / {tails[1]} |")
        L.append("")
        summ["tet"]["flipped_fraction"] = {k: v.get("flipped_tet_fraction") for k, v in T.items()}
        L += ["### Extreme unsmoothed tail from the tetrahedra (stream density ρ_T, N = 256)", "",
              "Mass-weighted quantiles 1 − 10⁻ᵏ of ρ_T; 'flipped' = fraction of inverted tetrahedra (shell-crossed mass).", "",
              "| model | flipped | 99.9% | 99.99% | 99.999% | 99.9999% | max |", "|---|---:|---:|---:|---:|---:|---:|"]
        for m in models:
            for suf in ("", "_paired"):
                g = T.get(f"{m}_N256{suf}", {}); r0 = g.get("R0")
                if not r0:
                    continue
                qt = dict(zip(r0["q_tail_k"], r0["q_tail"]))
                L.append(f"| {LBL[m]}{' (paired)' if suf else ''} | {100 * g['flipped_tet_fraction']:.2f}% | " +
                         " | ".join(f"{qt[k]:.3g}" if k in qt else "–" for k in (3, 4, 5, 6)) + f" | {r0['max']:.2g} |")
        L.append("")

    with open(os.path.join(RES, "summary.json"), "w") as f:
        json.dump(summ, f, indent=1)
    with open(os.path.join(RES, "tables.md"), "w") as f:
        f.write("\n".join(L) + "\n")
    print("\n".join(L))
    figures(S, R_, models)


def figures(S, R_, models):
    Rs = S["R"]; lb = np.array(S["LOGBINS"]); xc = 0.5 * (lb[1:] + lb[:-1])

    # slice: CIC vs sheet, raw 256^3 cells, N-body and 2LPT at N = 128 (thin slab)
    fig, ax = plt.subplots(2, 2, figsize=(9, 8.6), constrained_layout=True)
    for j, m in enumerate(("nbody", "2lpt")):
        for i, e in enumerate(P.EST):
            rho = np.load(P.rho_path(f"{m}_N128", e))
            sl = np.clip(rho[:, :, 100:102].mean(2), 1e-2, None)
            im = ax[i, j].imshow(sl.T, origin="lower", extent=[0, C.L, 0, C.L], cmap="magma",
                                 norm=LogNorm(vmin=0.1, vmax=30), interpolation="nearest")
            ax[i, j].set_title(f"{LBL[m]}, N = 128, {'CIC' if e == 'cic' else 'sheet (exact)'}", fontsize=9)
            ax[i, j].grid(False); ax[i, j].set_xlabel("x [Mpc/h]"); ax[i, j].set_ylabel("y [Mpc/h]")
    fig.colorbar(im, ax=ax, shrink=0.6, label="1 + δ (256³ cells, unsmoothed)")
    save(fig, "sheet_slice")

    # PDFs: N-body and 2LPT, both estimators, R_s = 7, 14
    for w, wl in (("V", "volume"), ("M", "mass")):
        fig, ax = plt.subplots(2, len(Rs), figsize=(3.2 * len(Rs), 5.2), sharex="col",
                               gridspec_kw=dict(height_ratios=[2.2, 1]))
        for j, R in enumerate(Rs):
            for m in ("nbody", "2lpt", "4lpt"):
                for e, ls in (("sheet", "-"), ("cic", "--")):
                    g = get(R_, f"{m}_N256", e, R)
                    ax[0, j].semilogy(xc, g["pdf" + w], color=C_ORD[m], ls=ls, lw=1.3,
                                      label=f"{LBL[m]} {e}" if j == 0 else None)
                a, b = get(R_, f"{m}_N256", "sheet", R), get(R_, f"{m}_N256", "cic", R)
                with np.errstate(divide="ignore", invalid="ignore"):
                    r = np.array(a["pdf" + w]) / np.array(b["pdf" + w]) - 1
                ok = np.array(b["pdf" + w]) > 1e-3
                ax[1, j].plot(xc[ok], r[ok], color=C_ORD[m], lw=1.3)
            ax[0, j].set_ylim(1e-3, None)
            ax[0, j].set_title(f"R_s = {R:g} Mpc/h" if R > 0 else "raw 1.17 Mpc/h cells")
            ax[1, j].axhline(0, color=INK, lw=0.6); ax[1, j].set_ylim(-0.3, 0.3)
            ax[1, j].set_xlabel("log₁₀(1+δ_R)")
            lo = xc[np.array(get(R_, "nbody_N256", "sheet", R)["pdf" + w]) > 1e-3]
            ax[0, j].set_xlim(lo.min() - 0.05, lo.max() + 0.05)
        ax[0, 0].set_ylabel(f"PDF ({wl}-weighted)"); ax[1, 0].set_ylabel("sheet / CIC − 1")
        ax[0, 0].legend(fontsize=6.5, ncol=1)
        save(fig, f"sheet_pdfs_{'vol' if w == 'V' else 'mass'}")

    # nLPT / N-body quantile ratios, sheet (filled) vs CIC (open)
    fig, ax = plt.subplots(2, len(Rs), figsize=(3.3 * len(Rs), 6.4), sharey="row")
    x = np.arange(len(QLAB))
    for i, w in enumerate(("V", "M")):
        for j, R in enumerate(Rs):
            for k, m in enumerate([mm for mm in models if mm != "nbody"]):
                for e, fill, dx in (("sheet", True, -0.12), ("cic", False, 0.12)):
                    a, b = get(R_, f"{m}_N256", e, R), get(R_, "nbody_N256", e, R)
                    y = 100 * (np.array(a["q" + w]) / np.array(b["q" + w]) - 1)
                    ax[i, j].plot(x + dx, y, "o-" if fill else "o--", color=C_ORD[m], ms=4, lw=1,
                                  mfc=C_ORD[m] if fill else "white",
                                  label=(f"{LBL[m]} {e}" if (i == 0 and j == 0) else None))
            ax[i, j].axhline(0, color=INK, lw=0.6)
            ax[i, j].set_xticks(x); ax[i, j].set_xticklabels(QLAB, rotation=45, fontsize=7)
            ax[i, j].set_title((f"R_s = {R:g} Mpc/h" if R > 0 else "raw cells") +
                               f" ({'volume' if w == 'V' else 'mass'})", fontsize=9)
            ax[i, j].set_ylim(-80, 60)
        ax[i, 0].set_ylabel("nLPT / N-body − 1 [%]")
    ax[0, 0].legend(fontsize=6, ncol=2)
    fig.text(0.5, -0.01, "filled, solid: phase-space sheet (exact) · open, dashed: CIC · same snapshots",
             ha="center", fontsize=8, color="#52514e")
    fig.tight_layout()
    save(fig, "sheet_quantiles")

    # estimator difference per model: sheet / CIC - 1 at quantiles, R_s = 7 and 14
    fig, ax = plt.subplots(2, 2, figsize=(8.4, 6), sharey="row")
    for i, w in enumerate(("V", "M")):
        for j, R in enumerate((0.0, 7.0)):
            for m in models:
                a, b = get(R_, f"{m}_N256", "sheet", R), get(R_, f"{m}_N256", "cic", R)
                ax[i, j].plot(x, 100 * (np.array(a["q" + w]) / np.array(b["q" + w]) - 1), "o-",
                              color=C_ORD[m], ms=4, lw=1.2, label=LBL[m] if (i == 0 and j == 0) else None)
            ax[i, j].axhline(0, color=INK, lw=0.6)
            ax[i, j].set_xticks(x); ax[i, j].set_xticklabels(QLAB, rotation=45, fontsize=7)
            ax[i, j].set_title((f"R_s = {R:g} Mpc/h" if R > 0 else "raw 1.17 Mpc/h cells") +
                               f" ({'volume' if w == 'V' else 'mass'})", fontsize=9)
        ax[i, 0].set_ylabel("sheet / CIC − 1 [%]")
    ax[0, 0].legend(fontsize=7)
    fig.tight_layout()
    save(fig, "sheet_estimator_diff")

    # gridless mass weighting: unsmoothed tetrahedron PDFs and nLPT / N-body with three weightings
    T = load_tet()
    if T:
        fig, ax = plt.subplots(1, 2, figsize=(10, 3.8))
        wb = np.linspace(-2.0, 8.0, 401); wc = 0.5 * (wb[1:] + wb[:-1])
        for m in models:
            g = T.get(f"{m}_N256", {}).get("R0")
            if g:
                ax[0].semilogy(wc, g["pdfM_wide"], color=C_ORD[m], lw=1.4, label=f"{LBL[m]} tetrahedra")
        for e, ls in (("sheet", ":"), ("cic", "--")):          # raw cells, mass-weighted, same wide bins
            rho = np.load(P.rho_path("nbody_N256", e)).ravel().astype(np.float64)
            lr = np.log10(np.clip(rho, 1e-6, None))
            h, _ = np.histogram(lr, wb, weights=rho); cnt, _ = np.histogram(lr, wb)
            y = np.where(cnt >= 10, h / h.sum() / (wb[1] - wb[0]), np.nan)   # bins with < 10 cells dropped
            ax[0].semilogy(wc, y, color=C_ORD["nbody"], lw=1.1, ls=ls,
                           label=f"N-body {'sheet' if e == 'sheet' else 'CIC'} cells (≥ 10 cells/bin)")
            del rho
        g = T["nbody_N256"]["R0"]; pw = np.array(g["pdfM_wide"])            # fold-caustic slope guide
        i0 = np.argmin(np.abs(wc - 3.0)); xs = np.linspace(2.5, 6.0, 20)
        ax[0].semilogy(xs, pw[i0] * 10 ** (-(xs - wc[i0])), color="#8a8984", lw=0.9, ls="-.",
                       label="∝ ρ⁻¹ per log ρ (fold caustics, p_M ∝ ρ⁻²)")
        ax[0].set_ylim(1e-7, 3); ax[0].set_xlim(-1.2, 6.5); ax[0].set_xlabel("log₁₀ ρ (unsmoothed)")
        ax[0].set_ylabel("mass-weighted PDF"); ax[0].legend(fontsize=6.5)
        ax[0].set_title("unsmoothed: tetrahedron stream density vs 1.17 Mpc/h cells", fontsize=9)
        for m in [x for x in models if x != "nbody"]:
            for lab, fn, mk, fill, dx in (("tet", lambda R, mm=m: tetq(T, f"{mm}_N256", R) / tetq(T, "nbody_N256", R) - 1, "o", True, -0.2),
                                          ("sheet cells", lambda R, mm=m: np.array(get(R_, f"{mm}_N256", "sheet", R)["qM"]) / np.array(get(R_, "nbody_N256", "sheet", R)["qM"]) - 1, "s", False, 0.0),
                                          ("CIC cells", lambda R, mm=m: np.array(get(R_, f"{mm}_N256", "cic", R)["qM"]) / np.array(get(R_, "nbody_N256", "cic", R)["qM"]) - 1, "x", False, 0.2)):
                y = [100 * fn(R)[-1] for R in Rs]
                ax[1].plot(np.arange(len(Rs)) + dx, y, marker=mk, ls="-" if fill else ":", color=C_ORD[m], ms=5,
                           mfc=C_ORD[m] if fill else "white", lw=1,
                           label=f"{LBL[m]} {lab}" if m in ("2lpt", "4lpt") else None)
        ax[1].axhline(0, color=INK, lw=0.6)
        ax[1].set_xticks(np.arange(len(Rs))); ax[1].set_xticklabels(["raw"] + [f"{R:g}" for R in Rs[1:]])
        ax[1].set_xlabel("R_s [Mpc/h]"); ax[1].set_ylabel("nLPT / N-body − 1 at mass 99.9% [%]")
        ax[1].set_title("dense tail, three mass weightings", fontsize=9); ax[1].legend(fontsize=6, ncol=2)
        fig.tight_layout()
        save(fig, "sheet_tetmass")

    # convergence with particle number, both estimators
    fig, ax = plt.subplots(1, 3, figsize=(11.5, 3.2))
    for j, R in enumerate((0.0, 7.0, 14.0)):
        for m in ("nbody", "2lpt", "4lpt"):
            for e, ls, mk in (("sheet", "-", "o"), ("cic", "--", "s")):
                ref = get(R_, f"{m}_N256", e, R)
                ys = []
                for n in (64, 128):
                    g = get(R_, f"{m}_N{n}", e, R)
                    ys.append(100 * np.max(np.abs(np.array(g["qV"])[1:-1] / np.array(ref["qV"])[1:-1] - 1)))
                ax[j].semilogy([64, 128], ys, ls=ls, marker=mk, color=C_ORD[m], ms=4,
                               mfc=C_ORD[m] if e == "sheet" else "white", label=f"{LBL[m]} {e}" if j == 0 else None)
        ax[j].set_xticks([64, 128]); ax[j].set_xlabel("N (particles per dimension)")
        ax[j].set_title((f"R_s = {R:g} Mpc/h" if R > 0 else "raw 1.17 Mpc/h cells") + ", volume-weighted", fontsize=9)
    ax[0].set_ylabel("max |quantile shift| vs N = 256 [%]"); ax[0].legend(fontsize=6.5, ncol=2)
    fig.tight_layout()
    save(fig, "sheet_convergence")


if __name__ == "__main__":
    main()
